type Service {
  Type: String!
  Ports: [ServicePort!]!
}

type ServicePort {
  Name: String!
  Port: Int!
  Protocol: String!
  NodePort: Int!
}

extend type Query {
  """
  Query log list
  """
  work_loglist(
    user: String!
    pod_id: Uint64!
    page: Int!
    size: Int!
  ): String!
  """
  Query Metric list
  """
  work_wetriclist(
    user: String!
    pod_id: Uint64!
    page: Int!
    size: Int!
  ): String!
  """
  Query Metric list
  """
  work_servicelist(
    user: String!
    pod_id: Uint64!
  ): [Service!]!

  """
  attestation_report_verify
  """
  attestation_report_verify(report: String!): Boolean!
}
