package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/wetee-dao/tee-dsecret/pkg/model"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	wmodel "wetee.app/worker/graph/model"
	"wetee.app/worker/internal/mint"
	"wetee.app/worker/internal/mint/proof"
	"wetee.app/worker/internal/store"
)

// WorkLoglist is the resolver for the work_loglist field.
func (r *queryResolver) WorkLoglist(ctx context.Context, user string, podID uint64, page int, size int) (string, error) {
	listCache, err := proof.ListLogsById(podID, page, 200, false)
	if err != nil {
		return "", gqlerror.Errorf("WorkLogList:" + err.Error())
	}

	nameSpace := mint.HexStringToSpace(user)

	// check is running
	pod, err := store.GetPod(podID)
	if err != nil && err.Error() != "the list not found" {
		return "", gqlerror.Errorf("GetPod:" + err.Error())
	}
	if pod != nil {
		list, err := mint.MinterIns.QueryLog(ctx, *pod, nameSpace, 0)
		if err != nil {
			return "", gqlerror.Errorf("QueryLog: " + nameSpace + " :" + err.Error())
		}
		listCache = append(listCache, proof.WorkLogProof{
			Time: uint64(time.Now().Unix()),
			Logs: list,
		})
	}

	bt, err := json.Marshal(listCache)
	if err != nil {
		return "", gqlerror.Errorf("JsonMarshal:" + err.Error())
	}

	return string(bt), nil
}

// WorkWetriclist is the resolver for the work_wetriclist field.
func (r *queryResolver) WorkWetriclist(ctx context.Context, user string, podID uint64, page int, size int) (string, error) {
	listCache, err := proof.ListMonitoringsById(podID, page, 200, false)
	if err != nil {
		return "", gqlerror.Errorf("WorkLogList:" + err.Error())
	}

	// check is running
	nameSpace := mint.HexStringToSpace(user)
	pod, err := store.GetPod(podID)
	if err != nil && err.Error() != "the list not found" {
		return "", gqlerror.Errorf("GetPod:" + err.Error())
	}
	if pod != nil {
		list, err := mint.MinterIns.QueryMetric(ctx, *pod, nameSpace)
		if err != nil {
			return "", gqlerror.Errorf("QueryMetric: " + err.Error())
		}

		listCache = append(listCache, proof.WorkCrProof{
			Time: uint64(time.Now().Unix()),
			Cr:   list,
		})
	}

	bt, err := json.Marshal(listCache)
	if err != nil {
		return "", gqlerror.Errorf("JsonMarshal:" + err.Error())
	}

	return string(bt), nil
}

// WorkServicelist is the resolver for the work_servicelist field.
func (r *queryResolver) WorkServicelist(ctx context.Context, user string, podID uint64) ([]*wmodel.Service, error) {
	name := mint.GetPodName(podID)

	nameSpace := mint.HexStringToSpace(user)
	client := mint.MinterIns.K8sClient
	ServiceSpace := client.CoreV1().Services(nameSpace)
	list, err := ServiceSpace.List(ctx, v1.ListOptions{
		LabelSelector: "service=" + name,
	})
	if err != nil {
		return nil, gqlerror.Errorf("WorkServiceList:" + err.Error())
	}

	var services []*wmodel.Service = make([]*wmodel.Service, 0, 10)
	if list != nil {
		for i := 0; i < len(list.Items); i++ {
			item := list.Items[i]
			var ports = make([]*wmodel.ServicePort, 0, len(item.Spec.Ports))
			for j := 0; j < len(item.Spec.Ports); j++ {
				ports = append(ports, &wmodel.ServicePort{
					Name:     item.ObjectMeta.Name,
					Port:     int(item.Spec.Ports[j].Port),
					Protocol: fmt.Sprint(item.Spec.Ports[j].Protocol),
					NodePort: int(item.Spec.Ports[j].NodePort),
				})
			}
			services = append(services, &wmodel.Service{
				Type:  fmt.Sprint(item.Spec.Type),
				Ports: ports,
			})
		}
	}

	return services, nil
}

// AttestationReportVerify is the resolver for the attestation_report_verify field.
func (r *queryResolver) AttestationReportVerify(ctx context.Context, report string) (bool, error) {
	reportx := strings.TrimPrefix(report, "0x")
	bt, err := hex.DecodeString(reportx)
	if err != nil {
		return false, gqlerror.Errorf("HexDecodeString:" + err.Error())
	}

	ps := model.TeeCall{}
	json.Unmarshal(bt, &model.TeeCall{})

	_, err = model.VerifyReport(&ps)
	if err != nil {
		return false, gqlerror.Errorf("VerifyLocalReport error:" + err.Error())
	}

	return true, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
