package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"encoding/hex"
	"fmt"

	"github.com/vektah/gqlparser/v2/gqlerror"
	module "github.com/wetee-dao/tee-dsecret/pkg/chains/pallets"
	dmodel "github.com/wetee-dao/tee-dsecret/pkg/model"
	"wetee.app/worker/graph/model"
	"wetee.app/worker/internal/mint"
	"wetee.app/worker/internal/mint/proof"
	"wetee.app/worker/internal/store"
)

// ClusterWithdrawal is the resolver for the cluster_withdrawal field.
// WorkerInfo is the resolver for the workerInfo field.
func (r *queryResolver) WorkerInfo(ctx context.Context) (*model.WorkerInfo, error) {
	root, err := store.GetRootUser()
	if err != nil {
		root = ""
	}
	var maddress = ""
	minter, _, _ := dmodel.GetP2PKey()
	if err == nil {
		maddress = minter.Address
	}

	report, _, err := proof.GetRemoteReport(minter, nil)
	if err != nil {
		report = nil
	}

	return &model.WorkerInfo{
		RootAddress: root,
		MintAddress: maddress,
		Report:      hex.EncodeToString(report),
	}, nil
}

// Worker is the resolver for the worker field.
func (r *queryResolver) Worker(ctx context.Context) ([]*model.Contract, error) {
	gsigner, _ := mint.MinterIns.PrivateKey.ToSigner()
	worker := &module.Worker{
		Signer: gsigner,
	}

	clusterID, err := store.GetClusterId()
	if err != nil {
		return nil, gqlerror.Errorf("Cant get cluster id:" + err.Error())
	}

	contracts, err := worker.GetClusterContracts(clusterID, nil)
	if err != nil {
		return nil, gqlerror.Errorf("GetClusterContracts:" + err.Error())
	}

	list := make([]*model.Contract, 0, len(contracts))
	for _, contract := range contracts {
		list = append(list, &model.Contract{
			StartNumber: fmt.Sprint(contract.ContractState.StartNumber),
			User:        hex.EncodeToString(contract.ContractState.User[:]),
			WorkID:      fmt.Sprint(contract.ContractState.WorkId.Id),
		})
	}
	return list, nil
}
