---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - secret.wetee.app
  resources:
  - apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.wetee.app
  resources:
  - apps/finalizers
  verbs:
  - update
- apiGroups:
  - secret.wetee.app
  resources:
  - apps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - secret.wetee.app
  resources:
  - gpus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.wetee.app
  resources:
  - gpus/finalizers
  verbs:
  - update
- apiGroups:
  - secret.wetee.app
  resources:
  - gpus/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - secret.wetee.app
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.wetee.app
  resources:
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - secret.wetee.app
  resources:
  - tasks/status
  verbs:
  - get
  - patch
  - update
