apiVersion: v1
kind: Service
metadata:
  name: wetee-node
  namespace: worker-addon
spec:
  clusterIP: None
  selector:
    app: wetee-node
  ports:
    - name: wetee-9944
      protocol: TCP
      port: 9944
      targetPort: 9944
