apiVersion: v1
kind: Service
metadata:
  name: wetee-dapp-service
  namespace: worker-addon
spec:
  type: NodePort
  selector:
    app: wetee-dapp
  ports:
    - name: http
      protocol: TCP
      nodePort: 30002
      port: 80
      targetPort: 80
