apiVersion: secret.wetee.app/v1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app-sample
    app.kubernetes.io/part-of: worker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: worker
  name: app-sample
spec:
  # TODO(user): Add fields here
