apiVersion: secret.wetee.app/v1
kind: Oracle
metadata:
  labels:
    app.kubernetes.io/name: oracle
    app.kubernetes.io/instance: oracle-sample
    app.kubernetes.io/part-of: worker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: worker
  name: oracle-sample
spec:
  # TODO(user): Add fields here
