// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginContent struct {
	Address   string `json:"address"`
	Timestamp int64  `json:"timestamp"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	Address   string `json:"address"`
	Timestamp int64  `json:"timestamp"`
}
