# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wetee-node-proxy
#   namespace: worker-addon
# spec:
#   selector:
#     matchLabels:
#       app: wetee-node-proxy
#   template:
#     metadata:
#       labels:
#         app: wetee-node-proxy
#     spec:
#       containers:
#         - name: c1
#           command:
#             - /bin/sh
#             - "-c"
#             - 'nginx -g "daemon off;" -c  /mnt/ssl-proxy/nginx.conf'
#           image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:latest
#           ports:
#             - containerPort: 443
#               name: wetee-node-443
#               protocol: TCP
#           volumeMounts:
#             - name: wetee-proxy
#               mountPath: /mnt/ssl-proxy
#       volumes:
#         - name: wetee-proxy
#           hostPath:
#             type: DirectoryOrCreate
#             path: /mnt/ssl-proxy
#       nodeSelector:
#         TEE: "SGX"

# ---
apiVersion: v1
kind: Service
metadata:
  name: wetee-chain-service
  namespace: worker-addon
spec:
  type: NodePort
  selector:
    app: wetee-node
  ports:
    - name: http
      protocol: TCP
      nodePort: 30001
      port: 443
      targetPort: 443
