apiVersion: apps/v1
kind: Deployment
metadata:
  name: wetee-dev
  namespace: worker-addon
spec:
  selector:
    matchLabels:
      app: wetee-dev
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wetee-dev
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/wetee_dao/wetee-node:dev.2025-08-27-19_50
          name: c1
          volumeMounts:
            - name: wetee-chain
              mountPath: /chain-data
        - name: c2
          image: nginx
          command:
            - /bin/sh
            - "-c"
            - 'nginx -g "daemon off;" -c  /mnt/ssl-proxy/nginx.conf'
          ports:
            - containerPort: 443
              name: wetee-dev-443
              protocol: TCP
          volumeMounts:
            - name: wetee-proxy
              mountPath: /mnt/ssl-proxy
        - name: sidecar
          image: parity/substrate-api-sidecar:latest
          env:
            - name: SAS_EXPRESS_KEEP_ALIVE_TIMEOUT
              value: "6000"
      volumes:
        - name: wetee-chain
          hostPath:
            type: DirectoryOrCreate
            path: /home/chain-data
        - name: wetee-proxy
          hostPath:
            type: DirectoryOrCreate
            path: /mnt/ssl-dev
      nodeSelector:
        TEE: "SGX"
