apiVersion: apps/v1
kind: Deployment
metadata:
  name: wetee-node
  namespace: worker-addon
spec:
  selector:
    matchLabels:
      app: wetee-node
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wetee-node
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/wetee_dao/wetee-node:dev.2024-06-20-11_42
          name: c1
          volumeMounts:
            - name: wetee-chain
              mountPath: /chain-data
        - name: c2
          command:
            - /bin/sh
            - "-c"
            - 'nginx -g "daemon off;" -c  /mnt/ssl-proxy/nginx.conf'
          image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
          ports:
            - containerPort: 443
              name: wetee-node-443
              protocol: TCP
          volumeMounts:
            - name: wetee-proxy
              mountPath: /mnt/ssl-proxy
      volumes:
        - name: wetee-chain
          hostPath:
            type: DirectoryOrCreate
            path: /home/wetee/Soft/chain_db
        - name: wetee-proxy
          hostPath:
            type: DirectoryOrCreate
            path: /mnt/ssl-proxy
      nodeSelector:
        TEE: "SGX"
