apiVersion: v1
kind: Service
metadata:
  name: wetee-chain-service
  namespace: worker-addon
spec:
  type: NodePort
  selector:
    app: wetee-node
  ports:
    - name: http
      protocol: TCP
      nodePort: 30001
      port: 9944
      targetPort: 9944
