apiVersion: apps/v1
kind: Deployment
metadata:
  name: wetee-node
  namespace: worker-addon
spec:
  selector:
    matchLabels:
      app: wetee-node
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wetee-node
    spec:
      containers:
        - image: wetee/wetee-node:dev.2024-04-17-09_47
          command:
            - /bin/sh
            - "-c"
            - "/usr/local/bin/wetee-node --dev -d /tmp/chain --rpc-external --rpc-methods=unsafe --unsafe-rpc-external --rpc-cors=all"
          name: c1
          ports:
            - containerPort: 9944
              name: wetee-node-9944
              protocol: TCP
          volumeMounts:
            - name: wetee-chain
              mountPath: /tmp/chain
      volumes:
        - name: wetee-chain
          hostPath:
            type: DirectoryOrCreate
            path: /mnt/chain
