apiVersion: apps/v1
kind: Deployment
metadata:
  name: wetee-node
  namespace: worker-addon
spec:
  selector:
    matchLabels:
      app: wetee-node
  template:
    metadata:
      labels:
        app: wetee-node
    spec:
      containers:
        - image: wetee/wetee-node:dev.2024-03-12-09_02
          name: c1
          ports:
            - containerPort: 9944
              name: wetee-node-9944
              protocol: TCP
