apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cvm-install
  namespace: kube-system
  generation: 1
spec:
  selector:
    matchLabels:
      k8s-app: cvm-install
  template:
    metadata:
      labels:
        k8s-app: cvm-install
    spec:
      nodeSelector:
        TEE: "SGX"
      containers:
        - image: wetee/cvm-deploy:x86_64-1cba83dba1fcc3f9e245761898d62e2a84fe1f0d
          imagePullPolicy: IfNotPresent
          name: cvm-install
          command:
            - /bin/bash
            - "-x"
            - "'/opt/confidential-containers-pre-install-artifacts/scripts/deploy.sh install'"
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/containerd/
              name: containerd-conf
            - mountPath: /opt/confidential-containers/
              name: kata-artifacts
            - mountPath: /var/run/dbus/system_bus_socket
              name: dbus
            - mountPath: /run/systemd/system
              name: systemd
            - mountPath: /usr/local/bin/
              name: local-bin
      volumes:
        - hostPath:
            path: /etc/containerd/
            type: ""
          name: containerd-conf
        - hostPath:
            path: /opt/confidential-containers/
            type: DirectoryOrCreate
          name: kata-artifacts
        - hostPath:
            path: /var/run/dbus/system_bus_socket
            type: ""
          name: dbus
        - hostPath:
            path: /run/systemd/system
            type: ""
          name: systemd
        - hostPath:
            path: /usr/local/bin/
            type: ""
          name: local-bin
