apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgx-pccs-api
  namespace: worker-addon
spec:
  selector:
    matchLabels:
      app: sgx-pccs-api
  template:
    metadata:
      labels:
        app: sgx-pccs-api
    spec:
      containers:
        - image: wetee/pccs:latest
          name: c1
          env:
            - name: APIKEY
              value: 8d375b775de84c2593e7694dedbbbe90
          ports:
            - containerPort: 8081
              name: wetee-pccs-8081
              protocol: TCP
