apiVersion: v1
kind: Service
metadata:
  name: sev-kbs-service
  namespace: worker-addon
spec:
  clusterIP: None
  selector:
    app: sev-kbs-api
  ports:
    - name: http
      protocol: TCP
      port: 44444
      targetPort: 44444
